services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        NEXT_PUBLIC_GRAPHQL_URL: "/graphql"
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
