services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    ports:
      - "3001:3001"
    volumes:
      - ../:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
