
services:

  postgres:
    build:
      context: ./backend/docker       
      dockerfile: Dockerfile.postgres
    ports: ["5433:5432"]
    environment:
      POSTGRES_USER: vector
      POSTGRES_PASSWORD: lakshay
      POSTGRES_DB: maps
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vector -d maps"]
      interval: 15s
      timeout: 5s
      retries: 5
  
  osm_import:
    build:
      context: ./backend/docker
      dockerfile: Dockerfile.import
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./backend/data/coastline:/data/coastline:ro
      - ./backend/data/country:/data/country:ro
      - ./backend/data/states:/data/states:ro
    environment:
      PGHOST: postgres
      PGUSER: vector
      PGPASSWORD: lakshay
      PGDATABASE: maps

  backend:
    build:
      context: ./backend             
      dockerfile: docker/Dockerfile     
    depends_on:
      postgres:
        condition: service_healthy
    ports: ["4000:4000"]
    env_file:
      - ./backend/.env
    environment:
      - DATABASE_URL=postgresql://vector:lakshay@postgres:5432/maps?sslmode=disable

  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: cloudbeaver
    restart: always
    depends_on: [postgres]
    ports: ["8080:8978"]
    environment:
      CB_SERVER_NAME: "CloudBeaver"
      CB_ADMIN_NAME: "admin"
      CB_ADMIN_PASSWORD: "admin"
    volumes:
      - cloudbeaver_data:/opt/cloudbeaver/workspace

  web:
    container_name: web
    build:
      context: ./frontend
      dockerfile: docker/Dockerfile
    ports: ["3001:3001"]
    environment:
      - NODE_ENV=production
    depends_on: [backend]

volumes:
  postgres_data:
  cloudbeaver_data:
