FROM postgis/postgis:15-3.3

RUN apt-get update \
  && apt-get install -y --no-install-recommends postgresql-15-pgrouting \
  && rm -rf /var/lib/apt/lists/*

COPY init-extensions.sql /docker-entrypoint-initdb.d/init-extensions.sql
COPY alter-system.sql /docker-entrypoint-initdb.d/alter-system.sql
